package main

type Fetch string

const (
	// DbStats - returns database statistics.
	DbStats Fetch = "Stats"

	// ProtoMLastInsertIdoduleConfOk - returns the integer generated by the database
	// in response to a command. Typically this will be from an
	// "auto increment" column when inserting a new row. Not all
	// databases support this feature, and the syntax of such
	// statements varies.

	// TODO seems not supported by MySQL
	LastInsertId Fetch = "LastInsertId"

	// RowsAffected - returns the number of rows affected by an update, insert, or delete.
	RowsAffected Fetch = "RowsAffected"

	// Columns - returns the column names.
	Columns Fetch = "Columns"

	// Rows - returns a array with maps containing "column name: value"
	Rows Fetch = "Rows"
)