package main

type Fetch string

const (
	// DbStats - returns database statistics.
	DbStats Fetch = "DbStats"

	// LastInsertId - returns the integer generated by the database
	// in response to a command. Typically this will be from an
	// "auto increment" column when inserting a new row.
	LastInsertId Fetch = "LastInsertId"

	// RowsAffected - returns the number of rows affected by an update, insert, or delete.
	RowsAffected Fetch = "RowsAffected"

	// Columns - returns a map containing "column name: column type"
	Columns Fetch = "Columns"

	// Rows - returns a array with maps containing "column name: value"
	Rows Fetch = "Rows"
)
